name: Compilar Executable (.exe)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Obtener codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Crear ejecutable limpio en un solo archivo
      run: |
        python -m venv venv
        venv\Scripts\activate
        pip install --upgrade pip
        pip install -r RESUMEN/requirements.txt
        cd RESUMEN
        pyinstaller --noconfirm --onefile --windowed --name "ReportesExcel" --add-data "templates;templates" --add-data "static;static" app.py

    - name: Subir ejecutable como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: ReportesExcel-Windows
        path: RESUMEN/dist/ReportesExcel.exe
